### ISSUE TITLE
My terminal emulator (mobaxterm) supports truecolor, but supports-color doesn't detect it

### ISSUE THREAD

**Issue by macau23** [chalk/supports-color#147]
How can I give you the information you need so that supports-color can correctly identify mobaxterm as supporting trucolor?

Related to https://github.com/dominikwilkowski/cfonts/issues/68

Currently I am working around it with `COLORTERM=truecolor`

**Comment by sindresorhus** [comment]
You must find out whether it exposes any environment variable we can use to detect such color support, or at minimum, we need an environment variable with the name of the terminal.

**Comment by macau23** [comment]
I can see no environment variable that exposes anything unique about my terminal emulator. Is there another way to detect it?

**Comment by Qix-** [comment]
Unfortunately not. Maybe supply the value of `TERM`?

The only workarounds otherwise are:

1. Continue setting COLORTERM in your shelll profile
2. Open a ticket with the emulator author(s) asking to expose some emulator-specific variable we can switch on.

Beyond that unfortunately TTYs are so archaic that there's not much else we can do :/
