### ISSUE TITLE
stdout.isTTY

### ISSUE THREAD

**Issue by yaycmyk** [chalk/supports-color#28]
https://github.com/chalk/supports-color/blob/master/index.js#L22

Could you provide a little context on why color should be disabled if it *isn't* TTY? Seems like it should be the other way around, or maybe I'm not understanding...

**Comment by jbnicolai** [comment]
Because `chalk` is a library for adding color to TTY output. Coloring, in the context of text streams, should be applied when the output is being displayed in the TTY and not when being piped into an other program or written to file.

**Comment by Qix-** [comment]
TTY = the thing you interact with as the end use (loosely stated). `cat somefile.txt | some-program` makes `cat` output to `some-program`'s stdin (*not* a TTY), and then `some-program` outputs to the user's terminal (your TTY), which means `some-program` can definitely write colors. Otherwise, `cat some-file.txt` might output ANSI colors to `some-program`, causing `some-program` to malfunction.

If that makes any sense :)
