### ISSUE TITLE
Mention supports-semigraphics?

### ISSUE THREAD

**Issue by stevenvachon** [chalk/supports-color#55]
[supports-semigraphics](https://npmjs.com/supports-semigraphics) was inspired by this library and might be informative to others if mentioned in the readme.

**Comment by sindresorhus** [comment]
The readme is not really clear about why and when I would need it. Can you show some realistic use-cases in your readme of when you would use it?

**Comment by stevenvachon** [comment]
A terminal progress bar or character spinner would be common examples of animated semigraphics.

**Comment by stevenvachon** [comment]
Readme updated.

**Comment by sindresorhus** [comment]
The detection in the module seems a bit fragile. Just because it supports unicode and is not a CI doesn't mean it supports animations, same with the inverse. Even the unicode checks are very unreliable. I also think the `animation` flag is to general. Would be better to use `--semigraphics`. I think this module would be a good case for checking against `terminfo` for capabilities related to animations. See: https://github.com/qix-/terminfo

Happy to receive a PR for adding it to the Related section when the above is resolved :)

**Comment by stevenvachon** [comment]
@sindresorhus [terminfo](https://npmjs.com/terminfo) is static for Windows, so it's just as fragile.

**Comment by Qix-** [comment]
@stevenvachon I agree. Terminfo needs to go IMO. We'll get there some day.

**Comment by stevenvachon** [comment]
@Qix- what's the alternative?
