### ISSUE TITLE
Support NO_COLOR environment variable

### ISSUE THREAD

**Issue by naholyr** [chalk/supports-color#74]
So that all CLIs based on this library (would make a lot) becomes directly compatible with [no-color manifesto](http://no-color.org/), how about adding support for `NO_COLOR` env variable? If ≠ empty string, then it sets `forceColor` to false.

**Comment by Qix-** [comment]
There are a million of these "manifestos" already, though. I don't see how this helps.

![](https://imgs.xkcd.com/comics/standards.png)

**Comment by Qix-** [comment]
Pray, tell me how it's an "over-exager[ation]". We get one of these at least per year, if not more frequently.

The point I'm trying to make is that this module is bloated. It's beginning to get hard to decide where things go, which things we should allow/disallow, etc. It's a kitchen sink of if statements.

What's worse is that _removing_ stale or outdated functionality always breaks somebody, which causes a ticket to open up at [chalk](/chalk/chalk) and a few other repositories linking to that ticket, us having to revert the feature here because we broke some small niche group of developers, and have to basically bloat not only the git history of _this_ repository, but of chalk as well - including polluting the releases on NPM.

Adding another manifesto just because someone wrote it and bought it a domain doesn't necessarily guarantee its 'fit' in a package. That's my argument.

---

This "manifest" solves **nothing** that wasn't already available.

- `FORCE_COLOR=0` for code that uses this module.
- `<cmd> | cat` for code that checks `isatty()` (including this module)
- `TERM=dummy` for code that checks `TERM` and/or uses `terminfo`/curses (most programs within the last **~40 years**)

**Comment by naholyr** [comment]
> It is non-critical that this is implemented. Therefore, I am strongly -1.

Would have been enough ;)

> > It brings immediate (small) value to users
> How?

It just allows users to know that whatever the coloring lib is used by their CLI tool, they can force/disable colors using a "standard" (trying to) environment variable. As a side-effect in this ideal world, CLI tools won't even have to worry about handling such option themselves.

But I agree it's absolutely non-critical, I've just been triggered by the initial intellectual dishonesty ;)
